@TodoApi_HostAddress = https://localhost:32768

GET {{TodoApi_HostAddress}}/todoitems

###

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk cat",
  "isComplete":false
}
###

PUT {{TodoApi_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "id": 1,
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{TodoApi_HostAddress}}/todoitems/1

###

GET {{TodoApi_HostAddress}}/todoitems/complete

###

GET {{TodoApi_HostAddress}}/todoitems/

###

GET {{TodoApi_HostAddress}}/todoitems/{id}

###

POST {{TodoApi_HostAddress}}/todoitems/

###

POST {{TodoApi_HostAddress}}/todoitems/

###
